### ISSUE TITLE
Session ID is now mandatory

### ISSUE THREAD

**Issue by BonarBeavis** [abeai/botkit-middleware-apiai#5]
Api.ai throws following error:

```
info: ERROR IN RECEIVE MIDDLEWARE:  Server response error with status code: 400
{
  "id": "3731547c-95d8-4366-b62f-75c1c4869ca6",
  "timestamp": "2016-11-23T12:32:28.93Z",
  "status": {
    "code": 400,
    "errorType": "bad_request",
    "errorDetails": "Required \u0027sessionId\u0027 parameter is empty."
  }
}
```

From the Readme of the [api.ai node wrapper](https://github.com/api-ai/api-ai-node-js):
```
var request = app.textRequest('<Your text query>', {
    sessionId: '<unique session id>'
});
```

Session Id is missing [here](https://github.com/abeai/botkit-middleware-apiai/blob/master/src/botkit-middleware-apiai.js#L19):
```
 if (message.text) {
  request = apiai.textRequest(message.text);

  request.on('response', function(response) {
```

**Comment by simpixelated** [comment]
I switched from https://github.com/api-ai/api-ai-botkit/ to this middleware and ran into the same error. Looks like api-ai-botkit has a [working sessionId example](https://github.com/api-ai/api-ai-botkit/blob/70805252f0a4e87dd32e4d66fa88fe3694b07ea8/api-ai-botkit.js#L72-L78) that maybe can be duplicated for this middleware.
